
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Mar  8 2021 09:29:08 IST (Mar  8 2021 03:59:08 UTC)

// Verification Directory fv/ADC_SAR1 

module ADC_SAR1(digital_out, out_flag, sample, value, cmp, clk, enable);
  input cmp, clk, enable;
  output [7:0] digital_out, value;
  output out_flag, sample;
  wire cmp, clk, enable;
  wire [7:0] digital_out, value;
  wire out_flag, sample;
  wire [7:0] result;
  wire [7:0] temp;
  wire [1:0] state;
  wire n_0, n_9, n_11, n_12, n_13, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37;
  DFFQX1 \result_reg[6] (.CK (clk), .D (n_32), .Q (result[6]));
  DFFQX1 \result_reg[0] (.CK (clk), .D (n_36), .Q (result[0]));
  DFFQX1 \result_reg[1] (.CK (clk), .D (n_29), .Q (result[1]));
  DFFQX1 \result_reg[3] (.CK (clk), .D (n_37), .Q (result[3]));
  DFFQX1 \result_reg[2] (.CK (clk), .D (n_30), .Q (result[2]));
  DFFQX1 \result_reg[5] (.CK (clk), .D (n_28), .Q (result[5]));
  DFFQX1 \result_reg[4] (.CK (clk), .D (n_33), .Q (result[4]));
  DFFQX1 \result_reg[7] (.CK (clk), .D (n_31), .Q (result[7]));
  AO22XL g1199__8780(.A0 (temp[3]), .A1 (n_35), .B0 (result[3]), .B1
       (n_34), .Y (n_37));
  DFFQX1 \temp_reg[4] (.CK (clk), .D (n_25), .Q (temp[4]));
  DFFQX1 \temp_reg[5] (.CK (clk), .D (n_27), .Q (temp[5]));
  DFFQX1 \temp_reg[6] (.CK (clk), .D (n_19), .Q (temp[6]));
  DFFQX1 \temp_reg[2] (.CK (clk), .D (n_21), .Q (temp[2]));
  DFFQX1 \temp_reg[1] (.CK (clk), .D (n_18), .Q (temp[1]));
  DFFQX1 \temp_reg[3] (.CK (clk), .D (n_22), .Q (temp[3]));
  AO22XL g1196__4296(.A0 (temp[0]), .A1 (n_35), .B0 (result[0]), .B1
       (n_34), .Y (n_36));
  AO22XL g1200__3772(.A0 (temp[4]), .A1 (n_35), .B0 (result[4]), .B1
       (n_34), .Y (n_33));
  AO22XL g1202__1474(.A0 (temp[6]), .A1 (n_35), .B0 (result[6]), .B1
       (n_34), .Y (n_32));
  AO22XL g1203__4547(.A0 (temp[7]), .A1 (n_35), .B0 (result[7]), .B1
       (n_34), .Y (n_31));
  AO22XL g1198__9682(.A0 (temp[2]), .A1 (n_35), .B0 (result[2]), .B1
       (n_34), .Y (n_30));
  AO22XL g1197__2683(.A0 (temp[1]), .A1 (n_35), .B0 (result[1]), .B1
       (n_34), .Y (n_29));
  AO22XL g1195__1309(.A0 (temp[5]), .A1 (n_35), .B0 (result[5]), .B1
       (n_34), .Y (n_28));
  DFFQX1 \temp_reg[0] (.CK (clk), .D (n_20), .Q (temp[0]));
  DFFQX1 \temp_reg[7] (.CK (clk), .D (n_17), .Q (temp[7]));
  AO22XL g1183__6877(.A0 (temp[5]), .A1 (n_24), .B0 (temp[6]), .B1
       (n_23), .Y (n_27));
  SDFFQX1 \digital_out_reg[4] (.CK (clk), .D (digital_out[4]), .SI
       (result[4]), .SE (n_26), .Q (digital_out[4]));
  SDFFQX1 \digital_out_reg[3] (.CK (clk), .D (digital_out[3]), .SI
       (result[3]), .SE (n_26), .Q (digital_out[3]));
  SDFFQX1 \digital_out_reg[1] (.CK (clk), .D (digital_out[1]), .SI
       (result[1]), .SE (n_26), .Q (digital_out[1]));
  SDFFQX1 \digital_out_reg[5] (.CK (clk), .D (digital_out[5]), .SI
       (result[5]), .SE (n_26), .Q (digital_out[5]));
  SDFFQX1 \digital_out_reg[0] (.CK (clk), .D (digital_out[0]), .SI
       (result[0]), .SE (n_26), .Q (digital_out[0]));
  SDFFQX1 \digital_out_reg[2] (.CK (clk), .D (digital_out[2]), .SI
       (result[2]), .SE (n_26), .Q (digital_out[2]));
  DFFQX1 \state_reg[1] (.CK (clk), .D (n_16), .Q (state[1]));
  AO22XL g1185__2900(.A0 (temp[4]), .A1 (n_24), .B0 (temp[5]), .B1
       (n_23), .Y (n_25));
  AO22XL g1184__2391(.A0 (temp[3]), .A1 (n_24), .B0 (temp[4]), .B1
       (n_23), .Y (n_22));
  AO22XL g1206__7675(.A0 (temp[2]), .A1 (n_24), .B0 (temp[3]), .B1
       (n_23), .Y (n_21));
  AO22XL g1204__7118(.A0 (temp[0]), .A1 (n_24), .B0 (temp[1]), .B1
       (n_23), .Y (n_20));
  AO22XL g1201__8757(.A0 (temp[6]), .A1 (n_24), .B0 (temp[7]), .B1
       (n_23), .Y (n_19));
  AO22XL g1205__1786(.A0 (temp[1]), .A1 (n_24), .B0 (temp[2]), .B1
       (n_23), .Y (n_18));
  SDFFQX1 \digital_out_reg[6] (.CK (clk), .D (digital_out[6]), .SI
       (result[6]), .SE (n_26), .Q (digital_out[6]));
  SDFFQX1 \digital_out_reg[7] (.CK (clk), .D (digital_out[7]), .SI
       (result[7]), .SE (n_26), .Q (digital_out[7]));
  OAI2BB1XL g1208__5953(.A0N (temp[7]), .A1N (n_15), .B0 (n_34), .Y
       (n_17));
  AND2X1 g1210__5703(.A (cmp), .B (n_23), .Y (n_35));
  DFFQX1 \state_reg[0] (.CK (clk), .D (n_13), .Q (state[0]));
  INVXL g1211(.A (n_24), .Y (n_16));
  CLKINVX1 g1215(.A (n_15), .Y (n_23));
  OAI21X1 g1213__7114(.A0 (n_11), .A1 (sample), .B0 (enable), .Y
       (n_24));
  AOI211X1 g1212__5266(.A0 (state[1]), .A1 (n_0), .B0 (n_12), .C0
       (state[0]), .Y (n_13));
  NOR2XL g1214__2250(.A (n_12), .B (n_9), .Y (n_26));
  NAND2XL g1217__6083(.A (n_11), .B (enable), .Y (n_15));
  NAND2XL g1216__2703(.A (sample), .B (enable), .Y (n_34));
  CLKINVX1 g1218(.A (n_9), .Y (out_flag));
  OR2X1 g1221__5795(.A (result[4]), .B (temp[4]), .Y (value[4]));
  OR2X1 g1224__7344(.A (result[6]), .B (temp[6]), .Y (value[6]));
  OR2X1 g1220__1840(.A (temp[0]), .B (result[0]), .Y (value[0]));
  OR2X1 g1228__5019(.A (result[2]), .B (temp[2]), .Y (value[2]));
  OR2X1 g1219__1857(.A (result[1]), .B (temp[1]), .Y (value[1]));
  OR2X1 g1226__9906(.A (result[7]), .B (temp[7]), .Y (value[7]));
  OR2X1 g1227__8780(.A (result[5]), .B (temp[5]), .Y (value[5]));
  OR2X1 g1225__4296(.A (result[3]), .B (temp[3]), .Y (value[3]));
  NAND2XL g1222__3772(.A (state[1]), .B (state[0]), .Y (n_9));
  NOR2BX1 g1223__1474(.AN (state[1]), .B (state[0]), .Y (n_11));
  NOR2BX1 g1229__4547(.AN (state[0]), .B (state[1]), .Y (sample));
  CLKINVX1 g1230(.A (enable), .Y (n_12));
  INVXL g1231(.A (temp[0]), .Y (n_0));
endmodule

