vpx set dofile abort exit
vpx set screen display -noprogress
tclmode

# Generated by Genus(TM) Synthesis Solution 18.10-p003_1, revision 1.293a
# Generated on: Mon Mar 08 09:29:08 IST 2021 (Mon Mar 08 03:59:08 GMT 2021)

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

# This composite dofile includes two compare operations: rtl-to-fv_map and
# fv_map-to-revised. The 'fv_map' netlist was automatically written in the
# verification directory during the syn_map command.

# This function is only valid for a flat compare
proc is_pass {} {
    redirect -variable compare_result {report_verification}
    foreach i [split $compare_result "\n"] {
        if {[regexp {Compare Results:\s+PASS} $i]} {
            return true
        }
    }
    return false
}

tcl_set_command_name_echo on

set_log_file logs_Mar08-09:29:03/rtl2final.lec.log -replace

usage -auto -elapse

# Comparing intermediate 'fv_map' netlist vs. revised netlist.

set_verification_information fv_map_ADC_SAR1_mv_db

read_implementation_information fv/ADC_SAR1 -golden fv_map -revised ADC_SAR1_mv

set_parallel_option -threads 4 -license "xl lp gxl lpgxl eco ecogxl" -norelease_license
set_compare_options -threads 4

set env(RC_VERSION)     "18.10-p003_1"
set env(CDN_SYNTH_ROOT) "/cad/GENUS181/tools.lnx86"
set CDN_SYNTH_ROOT      "/cad/GENUS181/tools.lnx86"
set env(CW_DIR) "/cad/GENUS181/tools.lnx86/lib/chipware"
set CW_DIR      "/cad/GENUS181/tools.lnx86/lib/chipware"

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_search_path ../lib -library -both
read_library -liberty -both   /root/201038012/First_Sem/project/learn/work/../lib/fast.lib

read_design -verilog95   -golden -lastmod -noelab fv/ADC_SAR1/fv_map.v.gz
elaborate_design -golden -root {ADC_SAR1}

read_design -verilog95   -revised -lastmod -noelab outputs_Mar08-09:29:03/ADC_SAR1_m.v
elaborate_design -revised -root {ADC_SAR1}

#add_name_alias fv/ADC_SAR1/fv_map.singlebit.original_name.alias.json.gz -golden
#set_mapping_method -alias -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

#add_name_alias fv/ADC_SAR1/ADC_SAR1_mv.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff -both

set_analyze_option -auto

set_system_mode lec
report_unmapped_points -summary
report_unmapped_points -extra -unreachable -notmapped
add_compared_points -all
compare

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_verification_information
report_verification_information


# Check intermediate 'fv_map' netlist vs. revised netlist compare result
if {![is_pass]} {
    error "// ERROR: Compare was not equivalent."
}

reset

# Comparing RTL vs. intermediate 'fv_map' netlist.

set_verification_information rtl_fv_map_db

read_implementation_information fv/ADC_SAR1 -revised fv_map

set_parallel_option -threads 4 -license "xl lp gxl lpgxl eco ecogxl" -norelease_license
set_compare_options -threads 4

set env(RC_VERSION)     "18.10-p003_1"
set env(CDN_SYNTH_ROOT) "/cad/GENUS181/tools.lnx86"
set CDN_SYNTH_ROOT      "/cad/GENUS181/tools.lnx86"
set env(CW_DIR) "/cad/GENUS181/tools.lnx86/lib/chipware"
set CW_DIR      "/cad/GENUS181/tools.lnx86/lib/chipware"

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_search_path ../lib -library -both
read_library -liberty -both   /root/201038012/First_Sem/project/learn/work/../lib/fast.lib

set_undriven_signal 0 -golden
set_naming_style rc -golden
set_naming_rule "%s\[%d\]" -instance_array -golden
set_naming_rule "%s_reg" -register -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -instance -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -variable -golden

# Align LEC's treatment of mismatched port widths with constant
# connections with Genus's. Genus message CDFG-467 and LEC message
# HRC3.6 may indicate the presence of this issue. This option is
# only available with LEC 17.20-d301 or later.
set lec_version_required "17.20301"
if {$lec_version >= $lec_version_required} {
    set_hdl_options -const_port_extend
}
set_hdl_options -VERILOG_INCLUDE_DIR "incdir:sep:src:cwd"

delete_search_path -all -design -golden
add_search_path ../rtl -design -golden
read_design   -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -verilog2k ../rtl/SAR_RTL.v
elaborate_design -golden -root {ADC_SAR1} -rootonly -rootonly  

read_design -verilog95   -revised -lastmod -noelab fv/ADC_SAR1/fv_map.v.gz
elaborate_design -revised -root {ADC_SAR1}

uniquify -all -nolib -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

#add_name_alias fv/ADC_SAR1/fv_map.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff -both

set_analyze_option -auto

write_hier_compare_dofile hier_tmp3.lec.do -noexact_pin_match -constraint -usage -replace -balanced_extraction -input_output_pin_equivalence -prepend_string " analyze_datapath -module -verbose ; analyze_datapath   -verbose; "
run_hier_compare hier_tmp3.lec.do -dynamic_hierarchy

report_verification -hier -verbose
set_system_mode lec
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}

write_verification_information
report_verification_information

tclmode
puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}
vpxmode
exit -f
