#==============================================================================
# Hierarchical dofile generated by Conformal LEC
# Version: 18.20-p100 (07-Nov-2018) (64 bit executable)
#------------------------------------------------------------------------------
# For additional reporting on 'not written' modules, see the 'VERBOSE REPORTING'
# section at the end of the hierarchical dofile
#------------------------------------------------------------------------------
# The command 'set module property' sets the instance context for the current
# root module. It is intended only for hierarchical comparison, and should
# not be modified by the user.
#------------------------------------------------------------------------------
# TERMS AND NOTATIONS USED
#------------------------------------------------------------------------------
# Module Instantiation Ratio: Average number of instantiations per matching module
# Periphery size: #Logic gates in the fanin and fanout cone of instance's input and output boundary, and bounded by key-points
# 0: Indicates pin is constant zero
# 1: Indicates pin is constant one
# X: Indicates pin is full DC
# U: Indicates pin is unreachable
# Z: Indicates pin is floating
# KP<--: Indicates pin's fanin is directly connected to key-point (ignores buffers/inverters)
# -->KP: Indicates pin's fanout is directly connected to key-point (ignores buffers/inverters)
# REP: Indicates pin is representative pin
# EQ_REP: <polarity> rep_pinname>: Indicates pin is a member EQ pin with
# 'rep_pinname' specifying the representative, and 'polarity' specifying
# if it is positive or negative equivalent
# = : Indicates that the pins on LHS and RHS are mapped
# + : Indicates positive polarity for pin mapping
# - : Indicates negative polarity for pin mapping
# ? : Indicates unknown polarity for pin mapping
# G: Indicates that the pin belongs to Golden
# R: Indicates that the pin belongs to Revised
# IN: Indicates that the pin is an Input pin
# OUT: Indicates that the pin is an Output pin
# IO: Indicates that the pin is an Inout pin. Polarity of Inout pin is
#     always '?' because of name-only mapping
#==============================================================================

set_system_mode setup
# Root Modules
# Comparing
#-------------------------------------------------------------------------------
# MODULE ADC_SAR1 (G) INSTANCE / (G)
# MODULE ADC_SAR1 (R) INSTANCE / (R)
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) cmp (REP)  =   (R) cmp (REP) (by name)
# IN (G) clk (REP)  =   (R) clk (REP) (by name)
# IN (G) enable (REP)  =   (R) enable (REP) (by name)
# RESOLVED Constraints
# OUT (G) digital_out[7] (REP)  =   (R) digital_out[7] (REP) (by name)
# OUT (G) digital_out[6] (REP)  =   (R) digital_out[6] (REP) (by name)
# OUT (G) digital_out[5] (REP)  =   (R) digital_out[5] (REP) (by name)
# OUT (G) digital_out[4] (REP)  =   (R) digital_out[4] (REP) (by name)
# OUT (G) digital_out[3] (REP)  =   (R) digital_out[3] (REP) (by name)
# OUT (G) digital_out[2] (REP)  =   (R) digital_out[2] (REP) (by name)
# OUT (G) digital_out[1] (REP)  =   (R) digital_out[1] (REP) (by name)
# OUT (G) digital_out[0] (REP)  =   (R) digital_out[0] (REP) (by name)
# OUT (G) out_flag (REP)  =   (R) out_flag (REP) (by name)
# OUT (G) sample (REP)  =   (R) sample (REP) (by name)
# OUT (G) value[7] (REP)  =   (R) value[7] (REP) (by name)
# OUT (G) value[6] (REP)  =   (R) value[6] (REP) (by name)
# OUT (G) value[5] (REP)  =   (R) value[5] (REP) (by name)
# OUT (G) value[4] (REP)  =   (R) value[4] (REP) (by name)
# OUT (G) value[3] (REP)  =   (R) value[3] (REP) (by name)
# OUT (G) value[2] (REP)  =   (R) value[2] (REP) (by name)
# OUT (G) value[1] (REP)  =   (R) value[1] (REP) (by name)
# OUT (G) value[0] (REP)  =   (R) value[0] (REP) (by name)
set_root_module ADC_SAR1 -Golden
set_root_module ADC_SAR1 -Revised
set_module_property -instance / -Golden
set_module_property -instance / -Revised
report_black_box -NOHidden
set_system_mode lec
 analyze_datapath -module -verbose ; analyze_datapath   -verbose; 
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
usage
report_hier_compare_result
report_hier_compare_result -Nonequivalent
report_hier_compare_result -Abort
report_hier_compare_result -Uncompared
# _END_OF_LEC_HIERARCHICAL_DOFILE_
